service:
  name: product-service

# app and org for use with dashboard.serverless.com
app: forever
org: jngisiro

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    DYNAMODB_PRODUCT_TABLE: products

functions:
  create:
    handler: src/handlers/create.handler
    events:
      - http:
          method: post
          path: /api/v1/product
