ProductsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: Products-${opt:stage}
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    BillingMode: PAY_PER_REQUEST
