ProductsTableIAM:
  Effect: 'Allow'
  Action:
    - dynamodb:PutItem
    - dynamodb:Scan*
    - dynamodb:GetItem
    - dynamodb:UpdateItem
    - dynamodb:DeleteItem
  Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/Products-${opt:stage}
