ProductsTableIAM:
  Effect: 'Allow'
  Action:
    - dynamodb:PutItem
    - dynamodb:Scan*
    - dynamodb:GetItem
    - dynamodb:UpdateItem
    - dynamodb:DeleteItem
  Resource:
    - ${self:custom.ProductsTable.arn}
